// src/app/layout.tsx

import { Amplify } from 'aws-amplify';  // Importamos Amplify
import awsconfig from "../aws-exports"; // Ajusta la ruta según la ubicación de tu archivo aws-exports.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Configura AWS Amplify aquí
Amplify.configure(awsconfig);

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
